### ISSUE TITLE
Lock down reading date and station fields for editing

### ISSUE THREAD

**Issue by rdawes1** [ChesapeakeCommons/fosr-admin#1]

**Comment by brendandm** [comment]
These fields are not editable. Subject to change pending approval by FOSR.

**Comment by brendandm** [comment]
After discussing this further, we decided to expose all fields for editing and make users responsible for quality control.

**Comment by brendandm** [comment]
For individual readings, display the site and parameter at the top of the page and open the analysis date, collection date and value fields for editing. Use the standard date picker for the date inputs.

**Comment by brendandm** [comment]
Maintain the current configuration. Since the Water Window is not the ultimate source of truth for FOSR data, the system shouldn't allow users to change these values.
