### ISSUE TITLE
Drainage and Karst Areas Are Not Saving

### ISSUE THREAD

**Issue by rdawes1** [ChesapeakeCommons/fosr-admin#20]

**Comment by brendandm** [comment]
This is fixed (to be confirmed).

![screenshot 2016-03-01 09 51 55](https://cloud.githubusercontent.com/assets/5325391/13430897/1716a49a-df95-11e5-8275-c956e884603d.png)

**Comment by rdawes1** [comment]
Looks good.  I made changes to the site titled "myexample" and all worked well.
